### ISSUE TITLE
Align columns fails with this exact string

### ISSUE THREAD

**Issue by AlexLamson** [AlexLamson/DataWrangler#15]
String to reproduce error:
```
ReportId, ActivityId, Name, GroupId, CommonGroupId, GroupListId, CommonGroupListId, IsActive, IsBillable, StartLocalTime, StartUtcTime, EndLocalTime, EndUtcTime, Notes, RelatedActivityId, SourceId, CurrentChangeSequence, CurrentChangeRandomValue, Other
(3, 611, 'ReportId, ActivityId, Name, GroupId, CommonGroupId • (Quantified Self, manictime sample) - Sublime Text (UNREGISTERED)', 62, 12, None, None, 1, None, '2018-06-27 13:39:31', '2018-06-27 17:39:31', '2018-06-27 13:39:36', '2018-06-27 17:39:36', None, None, None, 1500, 1218390469, '{}')

```

Stack trace:
```Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 1072, in run_
    return self.run(edit)
  File "C:\Users\Alex\AppData\Roaming\Sublime Text 3\Packages\User\DataWrangler.py", line 205, in run
    column_widths = detect_col_widths(self, sep, num_columns)
  File "C:\Users\Alex\AppData\Roaming\Sublime Text 3\Packages\User\DataWrangler.py", line 59, in detect_col_widths
    column_widths[i] = max(len(cell_string), column_widths[i])
IndexError: list index out of range
````

**Comment by AlexLamson** [comment]
The problem may be related to "d • (" in the middle of the text. Should look into this later
